--- 
- name: Testing Juniper and Ansible
  hosts: regress@10.221.132.35
  roles: 
   - Juniper.junos
  tasks: 
   - name: Retrieve Juniper facts
     junos_get_facts: host={{ ansible_ssh_host }}
     register: vmx_info
  
   - name: Print facts
     debug: msg="{{ vmx_info.facts }}"
